dataset: shapenet
pos_emb: null
ffm_map_scale: 16
ffm_map_size: 1024
hidden_features: 512
act_type: sine
w0: 30.0

model_type: functa
in_channels: 3
out_channels: 1
pred_type: voxel
use_meta_sgd: True
sampling: null
width: 64
depth: 4
norm_latents: false