input_dim: 3
output_dim: 1
model_type: inr_loe
hidden_dim: 64
num_hidden: 4
num_exps: [256, 256, 256, 256, 256]
ks: [8, 8, 8, 8, 8]
latent_size: 512
gate_type: separate
w0: 50.0
use_meta_sgd: false
outermost_linear: True
sampling: null
pred_type: voxel
std_latent: 0.0001
norm_latents: False
top_k: false
pos_emb: null
ffm_map_scale: 16
ffm_map_size: 1024