width: 64
depth: 4
w0: 50.0
hidden_features: 512
k_mixtures: 256
use_meta_sgd: True
outermost_linear: True
model_type: mnif
sampling: null
in_channels: 3
out_channels: 1
pred_type: voxel
embedding_type: null
use_latent_embedding: True
std_latent: 0.0001
mixture_type: layerwise
norm_latents: False
pos_emb: ffm
ffm_map_scale: 16
ffm_map_size: 1024